# Generated by Django 4.2.7 on 2023-11-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=120)),
                ("company_email", models.EmailField(max_length=254)),
                ("job_title", models.CharField(max_length=120)),
                ("job_description", models.TextField(max_length=300)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=6)),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("available", models.BooleanField()),
            ],
        ),
    ]
