# Generated by Django 4.2.7 on 2023-11-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0002_alter_quote_quote_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="context",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="quote",
            name="source",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
